// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy4W8Xg190KazCrDavOLgkTNzzXivP3Pw',
    appId: '1:659215095082:web:941dc8f77572e1ae23fa53',
    messagingSenderId: '659215095082',
    projectId: 'todo-423b4',
    authDomain: 'todo-423b4.firebaseapp.com',
    storageBucket: 'todo-423b4.appspot.com',
    measurementId: 'G-84645M8XZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgTWZ1Po9LreevbR3LcHNMohNm2egt_lg',
    appId: '1:659215095082:android:738b99b8230cf48523fa53',
    messagingSenderId: '659215095082',
    projectId: 'todo-423b4',
    storageBucket: 'todo-423b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjOmVBmp5oT8rKMV7oz9ezgElVk87Er1M',
    appId: '1:659215095082:ios:ad91eda1279a00d523fa53',
    messagingSenderId: '659215095082',
    projectId: 'todo-423b4',
    storageBucket: 'todo-423b4.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjOmVBmp5oT8rKMV7oz9ezgElVk87Er1M',
    appId: '1:659215095082:ios:ad91eda1279a00d523fa53',
    messagingSenderId: '659215095082',
    projectId: 'todo-423b4',
    storageBucket: 'todo-423b4.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy4W8Xg190KazCrDavOLgkTNzzXivP3Pw',
    appId: '1:659215095082:web:f1483b2988ef0c4423fa53',
    messagingSenderId: '659215095082',
    projectId: 'todo-423b4',
    authDomain: 'todo-423b4.firebaseapp.com',
    storageBucket: 'todo-423b4.appspot.com',
    measurementId: 'G-MVGNK2QBQE',
  );
}
